services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  mongo:
    image: mongo
    platform: linux/arm64
    ports:
      - 27017:27017

  invoice-service:
    build: ./invoice-service
    depends_on:
      - kafka
      - mongo
    ports:
      - 3001:3001

  order-service:
    build: ./order-service
    depends_on:
      - kafka
      - mongo
    ports:
      - 3002:3002

  notification-service:
    build: ./notification-service
    depends_on:
      - kafka
      - mongo
    ports:
      - 3003:3003

  frontend-api:
    build: ./frontend-api
    depends_on:
      - order-service
      - invoice-service
    ports:
      - 3000:3000
